// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     example.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

// Teste Kafka Golang
type MensagemSimples struct {
	// Hora que a mensagem foi gerada pelo consumidor!
	Hora_mensagem string `json:"hora_mensagem"`
}

const MensagemSimplesAvroCRC64Fingerprint = "JJ\xd4F\xe4 \xc4,"

func NewMensagemSimples() MensagemSimples {
	r := MensagemSimples{}
	return r
}

func DeserializeMensagemSimples(r io.Reader) (MensagemSimples, error) {
	t := NewMensagemSimples()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeMensagemSimplesFromSchema(r io.Reader, schema string) (MensagemSimples, error) {
	t := NewMensagemSimples()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeMensagemSimples(r MensagemSimples, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Hora_mensagem, w)
	if err != nil {
		return err
	}
	return err
}

func (r MensagemSimples) Serialize(w io.Writer) error {
	return writeMensagemSimples(r, w)
}

func (r MensagemSimples) Schema() string {
	return "{\"doc\":\"Teste Kafka Golang\",\"fields\":[{\"doc\":\"Hora que a mensagem foi gerada pelo consumidor!\",\"name\":\"hora_mensagem\",\"type\":\"string\"}],\"name\":\"teste.MensagemSimples\",\"type\":\"record\"}"
}

func (r MensagemSimples) SchemaName() string {
	return "teste.MensagemSimples"
}

func (_ MensagemSimples) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ MensagemSimples) SetInt(v int32)       { panic("Unsupported operation") }
func (_ MensagemSimples) SetLong(v int64)      { panic("Unsupported operation") }
func (_ MensagemSimples) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ MensagemSimples) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ MensagemSimples) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ MensagemSimples) SetString(v string)   { panic("Unsupported operation") }
func (_ MensagemSimples) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *MensagemSimples) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Hora_mensagem}

		return w

	}
	panic("Unknown field index")
}

func (r *MensagemSimples) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *MensagemSimples) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ MensagemSimples) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ MensagemSimples) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ MensagemSimples) HintSize(int)                     { panic("Unsupported operation") }
func (_ MensagemSimples) Finalize()                        {}

func (_ MensagemSimples) AvroCRC64Fingerprint() []byte {
	return []byte(MensagemSimplesAvroCRC64Fingerprint)
}

func (r MensagemSimples) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["hora_mensagem"], err = json.Marshal(r.Hora_mensagem)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *MensagemSimples) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["hora_mensagem"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Hora_mensagem); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for hora_mensagem")
	}
	return nil
}
